(** Re-exports of Rocq APIs under their Ltac2 name. *)

open Names
open Ltac2_plugin

(** {1 Built-in types} *)

type ident = Id.t
type uint63 = Uint63.t
type evar = Evar.t
type sort = Sorts.t
type cast = Constr.cast_kind
type instance = EConstr.EInstance.t
type constant = Constant.t
type inductive = Ind.t
type constructor = Construct.t
type projection = Projection.t
type pattern = Pattern.constr_pattern
type constr = EConstr.t
type preterm = Ltac_pretype.closed_glob_constr
type binder = Name.t EConstr.binder_annot * EConstr.types
type message = Pp.t
type err = Exninfo.iexn
type iexn = Exninfo.iexn
type exninfo = Exninfo.info

(** {1 Ltac2 APIs} *)

(** {2 Constants} *)

module Constant : sig
  type t = constant

  val equal : t -> t -> bool
  (** [equal c1 c2] tests equality of constants [c1] and [c2].

      Constants obtained through module aliases or Include are not considered
      equal by this function. *)

  val print : t -> message
  (** [print c] prints the constant using the shortest qualified identifier
      which refers to it. Does not avoid variable names in the current or global
      environment. *)
end

(** {2 Terms} *)

module Constr : sig
  type t = constr

  val type_ : Environ.env -> Evd.evar_map -> t -> Evd.evar_map * t
  (** [type_ env sigma t ] returns the type of [t] in the given environment
      and evar map. *)

  val equal : Evd.evar_map -> t -> t -> bool
  (** [equal sigma t1 t2] performs a strict syntactic comparison between [t1] and [t2],
      only up to α-conversion and evar expansion. *)

  module Binder : sig
    type t = binder
    type relevance = Sorts.relevance

    val make : Environ.env -> Evd.evar_map -> ident option -> constr -> (t, unit) result
    (** [make env sigma name typ] creates a binder given the name and the type of
        the bound variable. Fails if the type is not a type in the given environment. *)

    val unsafe_make : Name.t -> relevance -> constr -> t
    (** [unsafe_make name rel typ] creates a binder given the name, relevance,
        and type of the bound variable. *)

    val name : t -> Name.t
    (** [name binder] retrieves the name of the binder. *)

    val type_ : t -> constr
    (** [type_ binder] retrieves the type of the binder. *)

    val relevance : t -> relevance
    (** [relevance binder] retrieves the relevance of the binder. *)
  end

  module Relevance : sig
    type t = Binder.relevance
    (** Type of proof relevance: relevant, irrelevant or a variable (either
        locally rigid variable from sort polymorphism, or unification variable
        from elaboration). *)

    val equal : Evd.evar_map -> t -> t -> bool
    (** [equal sigma r1 r2] tests equality of relevances in the given evar map
        (the evar map matters for unification sort variables, which may be
        instantiated). *)

    val relevant : t
    (** Relevant relevance. *)

    val irrelevant : t
    (** Irrelevant relevance. *)
  end

  (** Low-level access to kernel terms. Use with care! *)
  module Unsafe : sig

    val kind : Evd.evar_map -> t -> (t, t, Evd.esorts, Evd.einstance, Evd.erelevance) Constr.kind_of_term
    (** [kind sigma t] returns the kind view of [t]. *)

    val make : (t, t, Evd.esorts, Evd.einstance, Evd.erelevance) Constr.kind_of_term -> t
    (** [make kind] constructs a term from the given kind. *)

    val check : Environ.env -> Evd.evar_map -> t -> Evd.evar_map * t
    (** [check env sigma t] checks that the term [t] generated by unsafe means
        is indeed safe in the current environment, and returns it.

        Raises if the check fails. *)

    val liftn : int -> int -> t -> t
    (** [liftn n k t] lifts by [n] indices greater than or equal to [k] in [t].
        Note that with respect to substitution calculi's terminology, [n] is the
        shift and [k] is the lift. *)

    val substnl : EConstr.Vars.substl -> int -> t -> t
    (** [substnl [r₁; …; rₙ] k t] substitutes in parallel [Rel(k+1); …; Rel(k+n)]
        with [r₁; …; rₙ] in [t]. *)

    val closenl : Evd.evar_map -> ident list -> int -> t -> t
    (** [closenl sigma [x₁; …; xₙ] k t] abstracts over variables [x₁; …; xₙ] and
        replaces them with [Rel(k); …; Rel(k+n-1)] in [t]. If two names are identical,
        the one of least index is kept. *)

    val closednl : Evd.evar_map -> int -> t -> bool
    (** [closednl sigma n t] is [true] iff [t] is a closed term under [n] binders. *)

    val noccur_between : Evd.evar_map -> int -> int -> t -> bool
    (** [noccur_between sigma n m t] returns [true] iff [Rel p] does not occur
        in term [t] for [n <= p < n+m]. *)

    type case = Constr.case_info

    val case : Environ.env -> inductive -> (case, unit) result
    (** [case env ind] generates the case information for a given inductive type. *)

    module Case : sig
      val equal : case -> case -> bool
      (** [equal case1 case2] checks equality of the inductive components of the
          case info. When comparing the inductives, those obtained through
          module aliases or Include are not considered equal by this
          function. *)

      val inductive : case -> inductive
      (** [inductive case] returns the inductive type being matched on in a
          pattern match expression. *)
    end
  end

  module Cast : sig
    type t = cast

    val default : t
    (** Default strategy for casts. *)

    val vm : t
    (** VM strategy for casts. *)

    val native : t
    (** Native strategy for casts. *)

    val equal : t -> t -> bool
    (** [equal c1 c2] tests equality of casts. *)
  end

  module Pretype : sig
    type expected_type = Pretyping.typing_constraint
    (** Typing constraints for pretyping. *)

    module Flags : sig
      type t = Pretyping.inference_flags
      (** Flags used to control pretyping. *)

      val constr_flags : t
      (** Flags used by [constr:(…)]. *)

      val set_use_coercion : bool -> t -> t
      (** Sets use of coercions during pretyping.

          [true] in [constr_flags]. *)

      val set_use_typeclasses : bool -> t -> t
      (** Sets whether to run typeclass inference at the end of pretyping and
          when needed according to the "Typeclass Resolution For Conversion"
          flag.

          [true] in [constr_flags]. *)

      val set_allow_evars : bool -> t -> t
      (** Sets whether to allow pretyping to produce new unresolved evars.

          [false] in [constr_flags]. *)

      val set_nf_evars : bool -> t -> t
      (** Sets whether to evar-normalize the result of pretyping. This should
          not impact anything other than performance.

          [true] in [constr_flags]. *)
    end

    val expected_istype : expected_type
    (** Pretyping constraint for terms expected to be types. *)

    val expected_oftype : constr -> expected_type
    (** Pretyping constraint for terms expected to have a specific type. *)

    val expected_without_type_constraint : expected_type
    (** No pretyping constraint. *)

    val pretype : Environ.env -> Evd.evar_map -> Flags.t -> expected_type -> preterm -> Evd.evar_map * constr
    (** [pretype env sigma flags type_constraint preterm] pretypes the given
        [preterm] using the pretyping flags and expected type constraint. *)
  end

  val has_evar : Evd.evar_map -> t -> bool
  (** [has_evar sigma t] returns [true] if [t] contains an evar. *)
end

(** {2 Constructor} *)

module Constructor : sig
  type t = constructor

  val equal : t -> t -> bool
  (** [equal c1 c2] tests equality of constructors. Constructors obtained
      through module aliases or Include are not considered equal by this
      function. *)

  val inductive : t -> inductive
  (** [inductive constructor] returns the inductive to which [constructor]
      belongs.  *)

  val index : t -> int
  (** [index constructor] returns the index of the given constructor (such that
      [c] is [Ind.get_constructor (Ind.data (inductive c)) (index c))]). *)

  val print : t -> message
  (** [print constructor] prints the constructor using the shortest qualified
      identifier which refers to it. Does not avoid variable names in the current or
      global environment. *)
end

(** {2 Control} *)

module Control : sig

  (** {3 Generic backtracking control} *)

  val throw : iexn -> 'a Proofview.tactic
  (** Fatal exception throwing. This does not induce backtracking. *)

  val zero : iexn -> 'a Proofview.tactic
  (** [zero e] raises the exception [e], passing control to the current
      backtracking continuation. *)

  val plus : 'a Proofview.tactic -> (iexn -> 'a Proofview.tactic) -> 'a Proofview.tactic
  (** Backtracking point. *)

  val once : 'a Proofview.tactic -> 'a Proofview.tactic
  (** [once t] behaves like [t], except it has at most one success: [once t]
      stops after the first success of [t]. If [t] fails with [e], [once t] also
      fails with [e]. If [once t; t'] fails on [t'], then [once t] will not
      backtrack and evaluate [t] for another value, and will instead fail. *)

  val case : 'a Proofview.tactic -> 'a Proofview.case Proofview.tactic
  (** [case] is the most general primitive to control backtracking:

      - If [t] would fail with [e], [case t] returns [Fail e].
      - If [t] would succeed and evaluate to [v] then [case t] returns [Next (v, h)],
        where [h] is the continuation to execute in case of subsequent
        failure. Calling [h] resets the backtrackable state to its value when
        case was called.

        [case] reifies a backtracking computation into an inspectable value, it
        allows the programmer to make explicit the effects which are normally
        implicit (i.e., they do not appear in the type system). *)

  (** {3 Proof state manipulation} *)

  val numgoals : int Proofview.tactic
  (** [numgoals] returns the number of goals currently focused. *)

  val dispatch : unit Proofview.tactic list -> unit Proofview.tactic
  (** [dispatch] is used to apply a different tactic to each goal under
      focus. It works by applying each of the tactics in a focus restricted to
      the corresponding goal (starting with the first goal).

      Fails when the length of the tactic list is not equal to the
      number of focused goals. *)

  val extend : unit Proofview.tactic list -> unit Proofview.tactic -> unit Proofview.tactic list -> unit Proofview.tactic
  (** [extend] is a more flexible variant of dispatch, where the second argument
      tactic is "repeated" enough times such that every goal has a tactic
      assigned to it. [extend b e r] applies the tactics in [b] to the first [length b]
      goals, the tactics in [r] to the last [length r] goals, and [e] to all tactics
      in between.

      Fails if [length b + length r] is greater than the number of goals under
      focus. *)

  val enter : unit Proofview.tactic -> unit Proofview.tactic
  (** [enter t] applies [t] in each goal under focus independently. *)

  val focus : int -> int -> 'a Proofview.tactic -> 'a Proofview.tactic
  (** [focus i j t] focuses a proofview on the goals from index [i] to index
      [j] (inclusive, goals are indexed from 1) and runs [t] with those goals under
      focus, i.e. goals number [i] to [j] become the only focused goals during the
      execution of [t]. When focus returns, the present focus is restored.

      If the range [i]–[j] is invalid, fails with a backtrackable "no such goal" error. *)

  val shelve : unit Proofview.tactic
  (** Shelve all goals under focus. The goals are placed on the shelf for later
      use, or to be solved by side-effects. *)

  val shelve_unifiable : unit Proofview.tactic
  (** Shelves the unifiable goals under focus, i.e. the goals which appear in
      other goals under focus (the unfocused goals are not considered). *)

  val unshelve : 'a Proofview.tactic -> 'a Proofview.tactic
  (** [unshelve t] runs [t] and unshelves existential variables added to the
      shelf by its execution, prepending them to the current goal. Returns the
      value produced by [t]. *)

  val new_goal : Proofview_monad.goal -> unit Proofview.tactic
  (** Adds the given evar to the list of goals as the last one. If it is already
      defined in the current state, don't do anything.

      Panics if the evar is not in the current state. *)

  val reorder_goals : int list -> unit Proofview.tactic
  (** [reorder_goals l] reorders the goals according to (1-indexed) list [l]:
      goal [i] after executing the tactic was goal [nth l (i-1)] before
      executing the tactic.

      Raises if [l] is not a permutation of ints from [1] to [numgoals]. *)

  val cycle : int -> unit Proofview.tactic
  (** If [n] is positive, [cycle n] puts the [n] first goal last. If [n] is
      negative, then it puts the [n] last goals first. *)

  val progress : 'a Proofview.tactic -> 'a Proofview.tactic
  (** [progress t] checks the state of the proof after [t]. It it is identical
      to the state before, then [progress t] fails, otherwise it succeeds like [t]. *)

  (** {3 Goal inspection} *)

  val goal : constr Proofview.tactic
  (** [goal] returns the conclusion of this goal.

      Fails if there is not exactly one goal under focus. *)

  val hyp : Environ.env -> variable -> (constr, unit) result
  (** [hyp env id] looks for the hypothesis or section variable in [env] with
      the given name. *)

  val hyp_value : Environ.env -> variable -> (constr option, unit) result
  (** [hyp_value env id] looks for the hypothesis or section variable with the
      given name in [env] and return its value ([v] in [H := v]) if there is
      one. *)

  val hyps : Environ.env -> (variable * constr option * constr) list
  (** [hyps env] returns the list of hypotheses and section variables in the
      environment [env]. *)

  (** {3 Refinement} *)

  val refine : (Evd.evar_map -> Evd.evar_map * constr) -> unit Proofview.tactic
  (** [refine t] computes the type of [t] in the current goal environment and
      evar map, and unifies the type with the current goal. All unification
      variables produced while computing [t] not solved by this unification
      process are added as new goals. *)

  (** {3 Evars} *)

  val with_holes : 'a Proofview.tactic -> ('a -> 'b Proofview.tactic) -> 'b Proofview.tactic
  (** [with_holes t f] evaluates [t], then applies [f] to the result, and fails
      if all evars generated by [t] have not been solved when [f] returns. *)

  (** {3 Timing} *)

  val time : string option -> 'a Proofview.tactic -> 'a Proofview.tactic
  (** Displays the time taken by a tactic to evaluate. *)

  val timeout : int -> 'a Proofview.tactic -> 'a Proofview.tactic
  (** [timeout n t] runs [t] with a timeout of [n] seconds. *)

  val timeoutf : float -> 'a Proofview.tactic -> 'a Proofview.tactic
  (** [timeoutf f t] runs [t] with a timeout of [f] seconds. *)

  (** {3 Misc} *)

  val abstract : ident option -> unit Proofview.tactic -> unit Proofview.tactic
  (** Abstract a subgoal. *)

  val check_interrupt : unit Proofview.tactic
  (** For internal use. *)

  val print_err : err -> message
  (** Print internal error. *)
end

(** {2 Environment} *)

module Env : sig
  val get : Libnames.full_path -> (GlobRef.t, unit) result
  (** [get path] returns the global reference corresponding to the absolute name
      given as argument, or [Error ()] if it does not exist. *)

  val path : GlobRef.t -> (Libnames.full_path, unit) result
  (** [path ref] returns the absolute name of the given reference, or [Error ()]
      if the reference does not exist. *)

  val expand : Libnames.qualid -> GlobRef.t list
  (** [expand qualid] returns the list of all global references whose absolute
      name contains the argument list as a suffix.  *)

  val instantiate : Environ.env -> Evd.evar_map -> GlobRef.t -> Evd.evar_map * constr
  (** [instantiate env sigma ref] returns a fresh instance of the corresponding
      reference, in particular generating fresh universe variables and constraints
      when this reference is universe-polymorphic. *)
end

(** {2 Fresh name generation} *)

module Fresh : sig
  module Free : sig
    type t = Nameops.Fresh.t
    (** Type of sets of free variables. *)

    val empty : t
    (** Empty set of free variables. *)

    val add : ident -> t -> t
    (** [add id s] adds the given identifier to the set of free variables [s]. *)

    val union : t -> t -> t
    (** [union s1 s2] merges the two sets of free variables. *)

    val of_ids : ident list -> t
    (** [of_ids ids] creates a set of free variables from the given list of identifiers. *)

    val of_constr : Evd.evar_map -> constr -> t
    (** [of_constr sigma t] collects all free variables of [t] as a set. *)
  end

  val fresh : Free.t -> ident -> ident
  (** [fresh free id] generates a fresh identifier with the given base name
      which is not a member of [free]. *)

  val next : Free.t -> ident -> ident * Free.t
  (** [next free id] generates a fresh identifier with the given base name which
      is not a member of [free], and returns the updated set. More efficient
      than composing [fresh] and [Free.add]. *)
end

(** {2 Identifiers} *)

module Ident : sig
  type t = ident

  val equal : ident -> ident -> bool
  (** [equal id1 id2] tests equality of identifiers. *)

  val to_string : ident -> string
  (** [to_string id] converts the identifier to a string. *)

  val of_string : string -> ident option
  (** [of_string s] converts the string to an identifier, returning [None] if
      the string contains invalid characters. *)
end

(** {2 Inductives} *)

module Ind : sig
  type t = inductive
  (** An inductive is the name of a mutually inductive type, along with
      the index of an inductive block within that type. *)

  type data = inductive * Declarations.mutual_inductive_body
  (** The actual data specified by a concrete declaration of an inductive type,
      containing, e.g., its constructors and its parameters. A value of type
      [data] corresponds to one inductive type within a larger mutually inductive
      block. *)

  val equal : t -> t -> bool
  (** Equality test for inductives. *)

  val data : Environ.env -> t -> data
  (** [data env ind] gets the data of [ind] in the environment [env]. *)

  val repr : data -> t
  (** [repr data] returns the name of the inductive type corresponding to the
      block. Inverse of [data]. *)

  val index : t -> int
  (** [index ind] returns the index of the inductive type inside its mutual
      block. Guaranteed to range between [0] and [nblocks data - 1] where [data]
      was retrieved using the above function. *)

  val nblocks : data -> int
  (** [nblocks data] returns the number of inductive types appearing in a mutual
      block. *)

  val nconstructors : data -> int
  (** [nconstructors data] returns the number of constructors appearing in the
      current block. *)

  val get_block : data -> int -> data option
  (** [get_block data n] is the block corresponding to the [n]th inductive type
      in data's parent mutually inductive type. Index must range between [0] and
      [nblocks data - 1], otherwise the function returns [None]. *)

  val get_constructor : data -> int -> constructor option
  (** [get_constructor data n] returns the [n]th constructor of the inductive
      type. Index must range between [0] and [nconstructors data - 1], otherwise the
      function returns [None]. *)

  val nparams : data -> int
  (** [nparams data] returns the number of parameters of the inductive type,
      including both uniform and non-uniform parameters. Does not count local
      let-ins. *)

  val nparams_uniform : data -> int
  (** [nparams_uniform data] returns the number of recursively uniform (i.e.,
      ordinary) parameters of the inductive type. *)

  val get_projections : data -> projection array option
  (** [get_projections data] returns the list of projections for a primitive
      record, or [None] if the inductive is not a primitive record. *)

  val constructor_nargs : data -> int array
  (** [(constructor_nargs data).(n)] is the number of non-parameter arguments
      accepted by the [n]th constructor of this inductive type. Add
      [(constructor_nargs data).(n)] to [nparams data] to get the total number of
      arguments of the constructor. *)

  val constructor_ndecls : data -> int array
  (** [(constructor_ndecls data).(n)] is the number of variables bound in a
      pattern match expression by the [n]th constructor of this inductive type. Can
      be greater than [constructor_nargs data] if the constructors have local
      let-bindings, e.g., applied to [Inductive Ind (A : Type) (f : A -> A) : Set := Constr (x : A) (y := f x)]
      it would return [[|2|]], because in [match t with Constr _ _ x y => e end],
      [x] and [y] are bound in [e]. *)

  val print : t -> message
  (** [print ind] prints the inductive using the shortest qualified identifier
      which refers to it. Does not avoid variable names in the current or global
      environment. *)
end

(** {2 Message} *)

module Message : sig
  val print : message -> unit
  (** [print msg] writes the message on the output stream. *)

  val empty : message
  (** [empty] is the empty message. *)

  val of_string : string -> message
  (** [of_string s] prints a string. *)

  val to_string : message -> string
  (** [to_string s] converts a message to a string. *)

  val of_int : int -> message
  (** [of_int n] prints an integer. *)

  val of_ident : ident -> message
  (** [of_ident id] prints an identifier. *)

  val of_constr : Environ.env -> Evd.evar_map -> constr -> message
  (** [of_constr env sigma t] prints [t] at level 8 (surrounding with parentheses to print syntax above that level such as applications). *)

  val of_lconstr : Environ.env -> Evd.evar_map -> constr -> message
  (** [of_lconstr env sigma t] prints [t] at level 200 (no surrounding parentheses). *)

  val of_preterm : Environ.env -> Evd.evar_map -> preterm -> message
  (** [of_preterm env sigma t] prints [t] at level 8 (surrounding with parentheses to print syntax above that level such as applications). *)

  val of_lpreterm : Environ.env -> Evd.evar_map -> preterm -> message
  (** [of_lpreterm env sigma t] prints [t] at level 200 (no surrounding parentheses). *)

  val of_exninfo : exninfo -> message
  (** [of_exninfo exninfo] prints the (Ltac2 and OCaml) backtrace info if it was recorded. *)

  val concat : message -> message -> message
  (** [concat m1 m2] concats two messages. *)

  (** {3 Boxing primitives}

      They are translated to OCaml "Format" boxes, see
      https://ocaml.org/docs/formatting-text.
   *)

  val force_new_line : message
  (** [force_new_line msg] forces writing on a new line after this. Warning:
      partially reinitialises the pretty-printing engine, potentially leading to bad
      printing afterwards. Prefer using a break hint inside a vertical box. *)

  val break : int -> int -> message
  (** General break hint: [break n i] either prints [n] spaces or splits the
      line adding [i] to the current indentation. *)

  val space : message
  (** Breaking space. Equivalent to break 1 0. *)

  val hbox : message -> message
  (** Horizontal box. Break hints in a horizontal box never split the line
      (nested boxes inside the horizontal box may allow line splitting). *)

  val vbox : int -> message -> message
  (** Vertical box. Every break hint in a vertical box splits the line. The int
      is added to the current indentation when splitting the line. *)

  val hvbox : int -> message -> message
  (** Horizontal/vertical box. Behaves as a horizontal box if it fits on a
      single line, otherwise behaves as a vertical box (using the given int). *)

  val hovbox : int -> message -> message
  (** Horizonal-or-vertical box. Prints as much as possible on each line,
      splitting the line at break hints when there is no more room on the line
      (see "Printing Width" option). The int is added to the indentation when
      splitting the line. *)
end

(** {2 Module} *)

module Module : sig
  type t = ModPath.t
  (** The name of a module or module type. It may be a functor. It may also be
      currently open. *)

  val equal : t -> t -> bool
  (** [equal m1 m2] tests equality of module names. *)

  val to_message : t -> message
  (** [to_message m] prints a module name. *)

  val is_modtype : Environ.env -> t -> bool
  (** [is_modtype env m] returns [true] if [m] is a module type or module type functor. *)

  val is_functor : Environ.env -> t -> bool
  (** [is_modtype env m] returns [true] if [m] is a module functor or module type functor. *)

  val is_bound_module : t -> bool
  (** [is_bound_module m] returns [true] for modules which are arguments of a
      currently open functor ([false] for submodules of bound modules). *)

  val is_library : t -> bool
  (** [is_library m] returns [true] for modules which are libraries (i.e. files). *)

  val is_open : t -> bool
  (** [is_open m] returns [true] if [m] refers to a currently open interactive
      module (or module type or functor). *)

  val parent_module : t -> t option
  (** [parent_module m] returns the parent module, i.e., [A] for [A.B]. Toplevel
      modules (libraries) and bound modules (functor arguments) return None. *)

  val module_of_reference : GlobRef.t -> t
  (** [module_of_reference ref] returns the module of the reference.

      Throws if [ref] is a [VarRef]. *)

  val current_module : unit -> t
  (** [current_module ()] returns a reference to the current innermost open
      interactive module. *)

  val loaded_libraries : unit -> t list
  (** [loaded_libraries ()] returns the list of loaded library modules. *)

  module Field : sig
    type t = Tac2ffi.ModField.t
  end

  val contents : t -> Field.t list option
  (** [contents m] returns the contents of the given module ([None] on closed
      functors and module types). Inductives are represented only by the first
      inductive of each mutual block (and no constructors). *)
end

(** {2 Pattern} *)

module Pattern : sig
  type context = Constr_matching.context
  (** A context is a constr with a hole, where the constr represents the surrounding
      context. *)

  val empty_context : context
  (** A trivial context ony made of the hole. *)

  val matches : Environ.env -> Evd.evar_map -> pattern -> constr -> Ltac_pretype.patvar_map option
  (** [matches env sigma pattern t] tries matching [t] against [pattern], and returns the
      assignment of pattern variables, or [None] if pattern-matching failed. *)

  val matches_subterm : pattern -> constr -> (context * Ltac_pretype.patvar_map) Proofview.tactic
  (** [matches_subterm pattern t] returns a stream of results corresponding to
      all of the subterms of [t] that matches [pattern] as in [matches], in the
      current goal. The stream is encoded as a backtracking value whose last
      exception is [Constr_matching.PatternMatchingFailure]. The additional
      value compared to [matches] is the context of the match, to be filled with
      the [instantiate] function. *)

  val matches_goal :
    bool ->
    Tac2match.match_context_hyps list ->
    Tac2match.match_pattern ->
    ((ident * Tac2match.context option option * Tac2match.context option) list *
       Tac2match.context option *
         Ltac_pretype.patvar_map)
      Proofview.tactic
  (** Given a list of patterns [hpats] for hypotheses and one pattern [cpat] for
      the conclusion, [matches_goal rev hpats cpat] produces (a stream of):

      - A list, with one element per pattern in [hpats], containing the name of the
        matched hypothesis, the context of the body pattern (or [None] if the
        body pattern was [MatchPattern]), and the context of the hypothesis pattern.
      - A context corresponding to the conclusion.
      - A substitution from pattern variables to terms.

      This produces a backtracking stream of results containing all the possible
      result combinations. The order of considered hypotheses is reversed if [rev]
      is true. *)

  val instantiate : context -> constr -> constr
  (** [instantiate context t] fills the hole of [context] with [t]. *)
end

(** {2 Projections} *)

module Proj : sig
  type t = projection
  (** Type of primitive projections. This includes the unfolding boolean. *)

  val equal : t -> t -> bool
  (** [equal p1 p2] tests equality of primitive projections.

      Projections obtained through module aliases or Include are not considered
      equal by this function. The unfolding boolean is not ignored. *)

  val ind : t -> inductive
  (** [ind proj] returns the inductive to which the projection belongs. *)

  val index : t -> int
  (** [index proj] returns the index of the projection indicates which field it
      projects. *)

  val unfolded : t -> bool
  (** [unfolded proj] returns the unfolding boolean. *)

  val set_unfolded : t -> bool -> t
  (** [set_unfolded proj unfolded] sets the unfolding boolean. *)

  val of_constant : constant -> t option
  (** [of_constant cst] gets the primitive projection associated to the
      constant. The returned projection is folded. Returns [None] when the
      constant is not associated to a primitive projection. *)

  val to_constant : t -> Projection.Repr.t option
  (** [to_constant proj] gets the constant associated to the
      primitive projection. Currently always returns [Some] but this may change
      in the future. *)

  val print : t -> message
  (** [print proj] prints the projection using the shortest qualified identifier
      which refers to it. Does not avoid variable names in the current or global
      environment.  *)
end

(** {2 Rewriting} *)

module Rewrite : sig

  (** Module for rewrite strategies used by [rewrite_strat]. *)
  module Strategy : sig
    type t = Rewrite.strategy

    val fail : t
    (** Failure. *)

    val id : t
    (** Success without progress. *)

    val refl : t
    (** Success with progress. *)

    val progress : t -> t
    (** Applies the argument and fails if no progress was made. *)

    val seq : t -> t -> t
    (** [seq left right] applies [left], and then [right] if [left] succeeded. *)

    val seqs : t list -> t
    (** Equivalent to [List.fold_left seq id]. *)

    val choice : t -> t -> t
    (** [choice left right] applies [left], and then [right] if [left] failed. *)

    val choices : t list -> t
    (** Equivalent to [List.fold_left choice fail]. *)

    val try_ : t -> t
    (** [try_ t] is equivalent to [choice t id]. *)

    val fix_ : Tac2val.closure -> t Proofview.tactic
    (** Fixed point operation for recursive strategies. [fix (fun f => s)]
        evaluates to [s [f / fix (fun f => s)]]. The function provided in the
        argument is executed only once when the strategy is constructed — it
        cannot be used to dynamically manage the rewriting. *)

    val any : t -> t
    (** Applies the argument until it fails. *)

    val repeat : t -> t
    (** [repeat s] is equivalent to [seq s (any s)]. *)

    val one_subterm : t -> t
    (** Applies the argument to the leftmost immediate subterm of the considered
        term on which progress can be made. *)

    val all_subterms : t -> t
    (** Applies the argument to all immediate subterms of the considered term, left-to-right.  *)

    val bottomup : t -> t
    (** Traverses the term bottom-up, left-to-right and applies the argument at
        each step as many times as possible. *)

    val topdown : t -> t
    (** Traverses the term top-down, left-to-right and applies the argument at
        each step as many times as possible. *)

    val innermost : t -> t
    (** Traverses the term bottom-up, left-to-right until the argument makes
        progress. *)

    val outermost : t -> t
    (** Traverses the term top-down--left-to-right until the argument makes
        progress. *)

    val hints : ident -> t
    (** Applies hints from rewrite hint database. *)

    val old_hints : ident -> t

    val one_lemma : preterm -> bool -> t
    (** Unifies the one side of the lemma with the current subterm and on
        success rewrite it to the other side. If the boolean argument is true,
        rewrites left-to-right; otherwise, rewrites right-to-left. *)

    val lemmas : preterm list -> t
    (** Equivalent to [choices (List.map (fun c => one_lemma c true)) l]. *)

    val fold : constr -> t
    (** Replaces the term under consideration with the argument if they unify. *)

    val eval : Redexpr.red_expr -> t
    (** Converts the term under consideration. *)

    val matches : pattern -> t
    (** The identity if the pattern matching succeeds, fails otherwise. *)

    val tactic : (constr -> constr -> constr option -> Rewrite.Result.t Proofview.tactic) -> t
    (** The [tactic f] strategy applies [f] to arguments [ty], [lhs] and [rel],
        where [lhs] is the subterm being rewritten, of type [ty], and an
        optional relation constraint [rel] is given.

        The tactic is applied to a single goal of type [unit] whose context
        corresponds to the context of the term to rewrite (i.e. the context of
        the goal at the start of the [rewrite_strat] call extended with the
        binders that were traversed to attain this subterm). The tactic should
        return a [Rewrite.Result.t] indicating success, failure or no progress and
        should *not* solve the goal. Solving the goal is an error that aborts
        the [rewrite_strat] call. The success record contains the chosen relation
        [rel], new right hand-side [rhs] and a proof [prf] of [rel t rhs].

        If the proof [prf] is syntactically [eq_refl _], then the witness of the rewriting
        is simply a *conversion* requiring no explicit proof and no congruence lemmas
        for the context of the rewrite. *)
  end

  val rewrite_strat : Strategy.t -> ident option -> unit Proofview.tactic
  (** Runs rewrite strategy on the type of a hypothesis or the goal if the
      second argument is [None]. *)
end

(** {2 Schemes} *)

module Scheme : sig
  type kind
  (** An abstract type representing a scheme kind. Use the predefined values
      below to refer to specific scheme kinds. *)

  val lookup : kind -> GlobRef.t -> GlobRef.t option
  (** [lookup kind ref] looks up the scheme registered under [kind] for the
      reference [ref]. Returns [None] if [ref] is not an inductive type or if no such
      scheme is registered. *)

  (** {3 Elimination schemes} *)

  val rect_dep : kind
  (** Dependent recursion scheme for Type. *)

  val rec_dep : kind
  (** Dependent recursion scheme for Set. *)

  val ind_dep : kind
  (** Dependent induction scheme for Prop. *)

  val sind_dep : kind
  (** Dependent induction scheme for SProp. *)

  val rect_nodep : kind
  (** Non-dependent recursion scheme for Type. *)

  val rec_nodep : kind
  (** Non-dependent recursion scheme for Set. *)

  val ind_nodep : kind
  (** Non-dependent induction scheme for Prop. *)

  val sind_nodep : kind
  (** Non-dependent induction scheme for SProp. *)

  (** {3 Case analysis schemes} *)

  val case_dep : kind
  (** Dependent case analysis scheme for Type. *)

  val case_nodep : kind
  (** Non-dependent case analysis scheme for Type. *)

  val casep_dep : kind
  (** Dependent case analysis scheme for Prop. *)

  val casep_nodep : kind
  (** Non-dependent case analysis scheme for Prop. *)

  val scase_nodep : kind
  (** Dependent case analysis scheme for SProp. *)

  val scase_dep : kind
  (** Non-dependent case analysis scheme for SProp. *)

  (** {3 Equality schemes} *)

  val sym : kind
  (** Symmetry scheme. *)

  val sym_involutive : kind
  (** Involutive symmetry scheme. *)

  val rew : kind
  (** Right-to-left rewriting scheme. *)

  val rew_dep : kind
  (** Right-to-left dependent rewriting scheme. *)

  val rew_fwd_dep : kind
  (** Right-to-left forward dependent rewriting scheme. *)

  val rew_r : kind
  (** Left-to-right rewriting scheme. *)

  val rew_r_dep : kind
  (** Left-to-right dependent rewriting scheme. *)

  val rew_fwd_r_dep : kind
  (** Left-to-right forward dependent rewriting scheme. *)

  val congr : kind
  (** Congruence scheme. *)

  (** {3 Boolean equality and decidability schemes} *)

  val beq : kind
  (** Boolean equality scheme. *)

  val dec_bl : kind
  (** Boolean to Leibniz equality scheme. *)

  val dec_lb : kind
  (** Leibniz to Boolean equality scheme. *)

  val eq_dec : kind
  (** Decidable equality scheme. *)
end

(** {2 Standard tactics} *)

module Std : sig
  type hypothesis = Tac2types.quantified_hypothesis
  type bindings = Tac2types.bindings
  type constr_with_bindings = Tac2types.constr_with_bindings
  type occurrences = Tac2types.occurrences
  type hyp_location_flag = Tac2types.hyp_location_flag
  type clause = Tac2types.clause
  type reference = GlobRef.t
  type strength = Genredexpr.strength
  type red_flags = Tac2types.red_flag
  type intro_pattern = Tac2types.intro_pattern
  and intro_pattern_naming = Tac2types.intro_pattern_naming
  and intro_pattern_action = Tac2types.intro_pattern_action
  and or_and_intro_pattern = Tac2types.or_and_intro_pattern
  type destruction_arg = Tac2types.destruction_arg
  type induction_clause = Tac2types.induction_clause
  type assertion = Tac2types.assertion
  type repeat = Equality.multi
  type orientation = Tac2types.orientation
  type rewriting = Tac2types.rewriting
  type evar_flag = Tac2types.evars_flag
  type advanced_flag = Tac2types.advanced_flag
  type move_location = Id.t Logic.move_location
  type inversion_kind = Inv.inversion_kind

  val intros : evar_flag -> intro_pattern list -> unit Proofview.tactic

  val apply :
    advanced_flag ->
    evar_flag ->
    (unit -> constr_with_bindings Proofview.tactic) list ->
    (ident * intro_pattern option) option ->
    unit Proofview.tactic

  val elim :
    evar_flag ->
    constr_with_bindings ->
    constr_with_bindings option ->
    unit Proofview.tactic

  val case : evar_flag -> constr_with_bindings -> unit Proofview.tactic

  val generalize :
    (constr * occurrences * Name.t) list ->
    unit Proofview.tactic

  val assert_ : assertion -> unit Proofview.tactic

  val enough :
    constr ->
    unit Proofview.tactic option option ->
    intro_pattern option ->
    unit Proofview.tactic
  (** TODO: Remove option option. *)

  val pose : Name.t -> constr -> unit Proofview.tactic

  val set :
    evar_flag ->
    (Name.t * constr) Proofview.tactic ->
    clause ->
    unit Proofview.tactic

  val remember :
    evar_flag ->
    Name.t ->
    constr ->
    intro_pattern_naming option ->
    clause ->
    unit Proofview.tactic

  val destruct :
    evar_flag ->
    induction_clause list ->
    constr_with_bindings option ->
    unit Proofview.tactic

  val induction :
    evar_flag ->
    induction_clause list ->
    constr_with_bindings option ->
    unit Proofview.tactic

  val exfalso : unit Proofview.tactic

  module Red : sig
    type t = Redexpr.red_expr

    val red : t
    val hnf : t

    val simpl : red_flags -> Tac2types.red_context -> t Proofview.tactic

    val cbv : red_flags -> t Proofview.tactic
    val cbn : red_flags -> t Proofview.tactic
    val lazy_ : red_flags -> t Proofview.tactic

    val unfold : (reference * occurrences) list -> t Proofview.tactic

    val fold : constr list -> t

    val pattern : (constr * occurrences) list -> t

    val vm : Tac2types.red_context -> t
    val native : Tac2types.red_context -> t
  end

  val eval_in : Red.t -> clause -> unit Proofview.tactic

  val eval : Red.t -> constr -> constr Proofview.tactic

  val change :
    pattern option ->
    (constr array -> constr Proofview.tactic) ->
    clause ->
    unit Proofview.tactic

  val rewrite :
    evar_flag ->
    rewriting list ->
    clause ->
    (unit -> unit Proofview.tactic) option ->
    unit Proofview.tactic

  val setoid_rewrite :
    orientation ->
    constr_with_bindings Proofview.tactic ->
    occurrences ->
    ident option ->
    unit Proofview.tactic

  val reflexivity : unit Proofview.tactic

  val assumption : unit Proofview.tactic
  val eassumption : unit Proofview.tactic
  val transitivity : constr -> unit Proofview.tactic
  val etransitivity : unit Proofview.tactic
  val cut : constr -> unit Proofview.tactic

  val left : evar_flag -> bindings -> unit Proofview.tactic

  val right : evar_flag -> bindings -> unit Proofview.tactic

  val constructor : evar_flag -> unit Proofview.tactic

  val split : evar_flag -> bindings -> unit Proofview.tactic

  val constructor_n : evar_flag -> int -> bindings -> unit Proofview.tactic

  val intros_until : hypothesis -> unit Proofview.tactic

  val symmetry : clause -> unit Proofview.tactic

  val rename : (ident * ident) list -> unit Proofview.tactic

  val revert : ident list -> unit Proofview.tactic

  val admit : unit Proofview.tactic

  val fix : ident -> int -> unit Proofview.tactic
  val cofix : ident -> unit Proofview.tactic

  val clear : ident list -> unit Proofview.tactic
  val keep : ident list -> unit Proofview.tactic

  val clearbody : ident list -> unit Proofview.tactic

  val exact_no_check :
    constr -> unit Proofview.tactic
  val vm_cast_no_check :
    constr -> unit Proofview.tactic
  val native_cast_no_check :
    constr -> unit Proofview.tactic

  val inversion :
    Inv.inversion_kind ->
    destruction_arg ->
    intro_pattern option ->
    ident list option ->
    unit Proofview.tactic

  val move : ident -> move_location -> unit Proofview.tactic

  val intro : ident option -> move_location option -> unit Proofview.tactic

  val specialize : constr_with_bindings -> intro_pattern option -> unit Proofview.tactic

  val discriminate : evar_flag -> destruction_arg option -> unit Proofview.tactic

  val injection : evar_flag -> intro_pattern list option -> destruction_arg option -> unit Proofview.tactic

  val absurd : constr -> unit Proofview.tactic
  val contradiction : constr_with_bindings option -> unit Proofview.tactic

  val autorewrite : bool -> unit Proofview.tactic option -> ident list -> clause -> unit Proofview.tactic

  val subst : ident list -> unit Proofview.tactic
  val subst_all : unit Proofview.tactic

  type debug = Hints.debug
  type strategy = Class_tactics.search_strategy

  val trivial : debug -> reference list -> ident list option -> unit Proofview.tactic

  val auto : debug -> int option -> reference list -> ident list option -> unit Proofview.tactic

  val eauto : debug -> int option -> reference list -> ident list option -> unit Proofview.tactic

  val typeclasses_eauto : strategy option -> int option -> ident list option -> unit Proofview.tactic

  val resolve_tc : constr -> unit Proofview.tactic

  val unify : constr -> constr -> unit Proofview.tactic

  val congruence : int option -> constr list option -> unit Proofview.tactic

  val simple_congruence : int option -> constr list option -> unit Proofview.tactic

  val f_equal : unit Proofview.tactic
end

(** {2 Transparent state} *)

module TransparentState : sig
  type t = TransparentState.t
  (** Type representing a transparency state. A transparency state is a set of
      variables, constants, and primitive projections. *)

  type strategy_level = Conv_oracle.level
  (** Strategy levels used by [with_strategy]:

      - [Expand] corresponds to the [-oo] level (always unfold)
      - [Opaque] corresponds to the [+oo] level (never unfold)
      - [Level n] corresponds to integer level [n] (where [Level 0] is
        transparent). *)

  val empty : t
  (** [empty] is the empty transparency state (all constants are opaque). *)

  val full : t
  (** [full] is the full transparency state (all constants are transparent).  *)

  val current : unit -> t Proofview.tactic
  (** [current ()] gives the transparency state of the goal, which is influenced
      by, e.g., the [Strategy] command, or the [with_strategy] tactic. *)

  val union : t -> t -> t
  (** [union t1 t2] builds a transparency state containing all the variables,
      constants, and primitive projections which are either in [t1] or in
      [t2]. *)

  val inter : t -> t -> t
  (** [inter t1 t2] builds a transparency state containing all the variables,
      constants, and primitive projections which are both in [t1] and in
      [t2]. *)

  val diff : t -> t -> t
  (** [diff t1 t2] builds a transparency state containing all the variables,
      constants, and primitive projections which are in [t1] but not in [t2]. *)

  val add_constant : constant -> t -> t
  (** [add_constant c t] adds the constant [c] to the transparency state
      [t]. Does nothing if the constant is already present. *)

  val add_proj : projection -> t -> t
  (** [add_proj p t] adds the primitive projection [p] to the transparency state
      [t]. Does nothing if the projection is already present. *)

  val add_var : ident -> t -> t
  (** [add_var v t] adds the local variable [v] to the transparency state
      [t]. Does nothing if the variable is already present. *)

  val remove_constant : constant -> t -> t
  (** [remove_constant c t] removes the constant [c] from the transparency state
      [t]. Does nothing if the constant is not present. *)

  val remove_proj : projection -> t -> t
  (** [remove_proj p t] removes the primitive projection [p] from the
      transparency state [t]. Does nothing if the projection is not present. *)

  val remove_var : ident -> t -> t
  (** [remove_var v t] removes the local variable [v] from the transparency
      state [t]. Does nothing if the variable is not present. *)

  val mem_constant : constant -> t -> bool
  (** [mem_constant c t] checks whether the constant [c] is present in the
      transparency state [t]. *)

  val mem_proj : projection -> t -> bool
  (** [mem_proj p t] checks whether the primitive projection [p] is present in
      the transparency state [t]. *)

  val mem_var : ident -> t -> bool
  (** [mem_var v t] checks whether the local variable [v] is present in the
      transparency state [t]. *)

  val with_strategy : strategy_level -> GlobRef.t list -> 'a Proofview.tactic -> 'a Proofview.tactic
  (** [with_strategy lvl refs tac] temporarily sets the strategy level of all
      references in [refs] to [lvl], executes [tac], and then restores the
      original strategy levels. This is the Ltac2 analogue of the
      [with_strategy] Ltac tactic and the [Strategy] vernacular command. *)
end

(** {2 Unification} *)

module Unification : sig
  type conv_flag = Evd.conv_pb
  (** Controls if cumulativity [Prop <= Set <= Type 1 <= … <= Type i <= …] is
      used for conversion. *)

  val conv : Environ.env -> Evd.evar_map -> conv_flag -> TransparentState.t -> constr -> constr -> Evd.evar_map option
  (** [conv env sigma flag ts c1 c2] returns [true] if both [c1] and [c2] are
      convertible, in which case it returns the updated environment with the universes
      constraints required for the terms to be convertible. It returns [None] if the
      terms are not convertible.

      [conv] is parametrised by:
      - [flag] which controls if conversion is done up to cumulativity or not.
      - [ts] which controls which constants get unfolded during conversion. *)

  val unify : TransparentState.t -> constr -> constr -> unit Proofview.tactic
  (** [unify ts c1 c2] unifies [c1] and [c2] (using Evarconv unification), which
      may have the effect of instantiating evars. If [c1] and [c2] cannot be
      unified, the tactic fails. *)

  val solve_constraints : unit Proofview.tactic
  (** [solve_constraints] solves any delayed unification constraints. *)
end
